# nombre del flujo de trabajo

name: Integración y entrega continua
on:

  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest  

    env:
      nombres: "Rodney Kevin"  
      apellidos: "Ruiz Pariona"  
      edad: "35"  

    steps:
      # Paso 1: Presentación
      - name: Presentación
        run: echo "Mi nombre es ${{ env.nombres }} ${{ env.apellidos }} y tengo ${{ env.edad }} años"

      # Paso 2: Datos generales
      - name: Datos generales
        run: echo "Carrera de ingeniería de sistemas"

      # Paso 3: Variables de entorno secretas
      - name: Variables de entorno secretas
        env:
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
        run: |
          echo "user: $user"
          echo "password: $password"

    
    
